<a href="https://colab.research.google.com/github/Idguerrero333/NOTEBOOKPYTHONINTERACTIVE/blob/main/ETL_PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas


## Leyendo archivos CSV

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd

In [ ]:
datos = pd.read_csv('/content/drive/MyDrive/CIENCIA DE DATOS/PANDAS/superstore_data.csv')

In [ ]:
datos.head()

Id  Year_Birth   Education Marital_Status   Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced  84835.0        0         0   
1      1        1961  Graduation         Single  57091.0        0         0   
2  10476        1958  Graduation        Married  67267.0        0         1   
3   1386        1967  Graduation       Together  32474.0        1         1   
4   5371        1989  Graduation         Single  21474.0        1         0   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   
3   11/5/2014        0        10  ...                0                 0   
4    8/4/2014        0         6  ...               11                 0   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   
3             0                  1                1                    0   
4            34                  2                3                    1   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  
3                  2                  7         0         0  
4                  2                  7         1         0  

[5 rows x 22 columns]

In [ ]:
datos_cinco_lineas = pd.read_csv('/content/drive/MyDrive/CIENCIA DE DATOS/PANDAS/superstore_data.csv', nrows= 5)

In [ ]:
datos_cinco_lineas

Id  Year_Birth   Education Marital_Status  Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced   84835        0         0   
1      1        1961  Graduation         Single   57091        0         0   
2  10476        1958  Graduation        Married   67267        0         1   
3   1386        1967  Graduation       Together   32474        1         1   
4   5371        1989  Graduation         Single   21474        1         0   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   
3   11/5/2014        0        10  ...                0                 0   
4    8/4/2014        0         6  ...               11                 0   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   
3             0                  1                1                    0   
4            34                  2                3                    1   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  
3                  2                  7         0         0  
4                  2                  7         1         0  

[5 rows x 22 columns]

In [ ]:
datos_importante_columnas = pd.read_csv('/content/drive/MyDrive/CIENCIA DE DATOS/PANDAS/superstore_data.csv', usecols = ['Id','Year_Birth','Income']) ##nombre de la columna con '' o posicion n

In [ ]:
datos_importante_columnas.head()

Id  Year_Birth   Income
0   1826        1970  84835.0
1      1        1961  57091.0
2  10476        1958  67267.0
3   1386        1967  32474.0
4   5371        1989  21474.0

In [ ]:
datos_punto_coma = pd.read_csv('/content/drive/MyDrive/CIENCIA DE DATOS/PANDAS/superstore_data_punto_coma.csv')

In [ ]:
datos_punto_coma.head()

Id;Year_Birth;Education;Marital_Status;Income;Kidhome;Teenhome;Dt_Customer;Recency;MntWines;MntFruits;MntMeatProducts;MntFishProducts;MntSweetProducts;MntGoldProds;NumDealsPurchases;NumWebPurchases;NumCatalogPurchases;NumStorePurchases;NumWebVisitsMonth;Response;Complain
0  1826;1970;Graduation;Divorced;84835;0;0;6/16/2...                                                                                                                                                                                                                             
1  1;1961;Graduation;Single;57091;0;0;6/15/2014;0...                                                                                                                                                                                                                             
2  10476;1958;Graduation;Married;67267;0;1;5/13/2...                                                                                                                                                                                                                             
3  1386;1967;Graduation;Together;32474;1;1;11/5/2...                                                                                                                                                                                                                             
4  5371;1989;Graduation;Single;21474;1;0;8/4/2014...

In [ ]:
datos_punto_coma = pd.read_csv('/content/drive/MyDrive/CIENCIA DE DATOS/PANDAS/superstore_data_punto_coma.csv', sep=';')

In [ ]:
datos_punto_coma.head()

Id  Year_Birth   Education Marital_Status   Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced  84835.0        0         0   
1      1        1961  Graduation         Single  57091.0        0         0   
2  10476        1958  Graduation        Married  67267.0        0         1   
3   1386        1967  Graduation       Together  32474.0        1         1   
4   5371        1989  Graduation         Single  21474.0        1         0   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   
3   11/5/2014        0        10  ...                0                 0   
4    8/4/2014        0         6  ...               11                 0   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   
3             0                  1                1                    0   
4            34                  2                3                    1   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  
3                  2                  7         0         0  
4                  2                  7         1         0  

[5 rows x 22 columns]

##Exportando archivos

In [ ]:
datos_importante_columnas.to_csv('/content/drive/MyDrive/CIENCIA DE DATOS/PANDAS/datos_importante_columnas.csv')

In [ ]:
datos_exportados = pd.read_csv('/content/drive/MyDrive/CIENCIA DE DATOS/PANDAS/datos_importante_columnas.csv')

In [ ]:
datos_exportados.head()

Unnamed: 0     Id  Year_Birth   Income
0           0   1826        1970  84835.0
1           1      1        1961  57091.0
2           2  10476        1958  67267.0
3           3   1386        1967  32474.0
4           4   5371        1989  21474.0

In [ ]:
datos_importante_columnas.to_csv('/content/drive/MyDrive/CIENCIA DE DATOS/PANDAS/datos_sin_index.csv', index=False)

In [ ]:
datos_exportados_sin_index = pd.read_csv('/content/drive/MyDrive/CIENCIA DE DATOS/PANDAS/datos_sin_index.csv')

In [ ]:
datos_exportados_sin_index.head()

Id  Year_Birth   Income
0   1826        1970  84835.0
1      1        1961  57091.0
2  10476        1958  67267.0
3   1386        1967  32474.0
4   5371        1989  21474.0

##Errores de codificacion
Podemos usar una biblioteca llamada chardet para detectar el encoding de un archivo CSV. Para usar esta biblioteca en Google Colab, simplemente importela:


```
import chardet
```


```
with open('datos.csv', 'rb') as file:
    print(chardet.detect(file.read()))
```

Al ejecutar el código Giovanna obtuvo el siguiente resultado:

{'encoding': 'UTF-16', 'confidence': 1.0, 'language': ''}

es probable que el archivo CSV esté codificado con UTF-16 con una confianza de 1.0. Para especificar la codificación correcta al cargar el archivo CSV con la biblioteca Pandas, puede utilizar un parámetro llamado encoding:


```
df = pd.read_csv('datos.csv', encoding='UTF-16')
```



#CHALLENGE 1

Es hora de que pongas a prueba los conocimientos desarrollados durante la clase. Disponemos de un archivo en formato CSV, el cual se obtuvo de la página Información de Salud (TABNET) - DATASUS. Este archivo contiene los gastos hospitalarios públicos de cada una de las Unidades de la Federación Brasileña desde enero de 2008 hasta marzo de 2021.

Su desafío aquí será leer este archivo usando la función read_csv de la biblioteca Pandas. Se deben agregar algunos parámetros para que la lectura se realice correctamente. Entonces, aquí hay algunos consejos:


1. Asegúrese de que el archivo CSV esté separado por una coma o punto y coma.
2. La codificación del archivo es ISO-8859-1.
3. Las primeras tres líneas del archivo se pueden ignorar, ya que el encabezado sólo comienza en la cuarta línea.
4. Las últimas 9 líneas también se pueden ignorar, ya que son sólo información sobre dónde se tomaron los datos.
5. Para eliminar las últimas líneas es necesario agregar el parámetro engine='python'.


In [ ]:
import chardet

In [ ]:
with open('/content/drive/MyDrive/CIENCIA DE DATOS/PANDAS/datos_sus.csv', 'rb') as file:
    print(chardet.detect(file.read()))

{'encoding': 'ISO-8859-1', 'confidence': 0.73, 'language': ''}


In [ ]:
url = '/content/drive/MyDrive/CIENCIA DE DATOS/PANDAS/datos_sus.csv'

In [ ]:
datos_FB = pd.read_csv(url, sep=';', encoding='ISO-8859-1', skiprows=3, skipfooter=9, engine='python')

In [ ]:
datos_FB.head()

Unidade da Federação     2008/Jan     2008/Fev     2008/Mar     2008/Abr  \
0             Rondônia   1388528,39   2931283,42   1541682,52   1525314,96   
1                 Acre    902416,00   1497206,26   1794028,48   1730469,42   
2             Amazonas   4735529,42   7118990,57   8196635,49   8259378,42   
3              Roraima    657889,53    777939,31    718688,03    839994,39   
4                 Pará  18864744,11  19553758,20  21937342,70  20842829,69   

      2008/Mai     2008/Jun     2008/Jul     2008/Ago     2008/Set  ...  \
0   1645953,84   1406150,68   3065279,01   3231494,61   3117178,63  ...   
1   1819443,92   1828496,00   2511754,59   2089107,14   2275708,53  ...   
2   7831399,90   8477273,62   9368858,72   9352532,70   9363099,35  ...   
3    862347,96    832440,66    996693,09    894271,18    910424,17  ...   
4  23249952,88  23240687,56  24002223,56  23341218,03  25172261,32  ...   

      2020/Jul     2020/Ago     2020/Set     2020/Out     2020/Nov  \
0  11824687,13  11733307,76  10201985,14   7955139,45   9357946,29   
1   3915193,20   3640142,82   3391242,21   4044321,44   3276590,10   
2  19769460,14  18059931,43  17841015,63  16408315,10  19895617,91   
3   3015488,30   2826486,18   2928043,91   3090313,73   3621031,05   
4  40804126,43  44385715,88  36820249,47  36965931,34  39004315,80   

      2020/Dez     2021/Jan     2021/Fev     2021/Mar          Total  
0   8880836,55   9266014,59   7730597,04  11023309,47   996411254,68  
1   3696997,31   3715723,12   3538427,92   4077045,92   450048530,47  
2  17765167,69  21430289,17  25917134,55  22032176,22  1917247936,05  
3   3454460,94   3266928,47   3519773,73   3985530,08   328876965,09  
4  38015145,79  38354682,46  37688314,23  33276392,89  4705309002,29  

[5 rows x 161 columns]

# Aula 2 leyendo archivos en excel

##importando archivo excel

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
archivo = '/content/drive/MyDrive/CIENCIA DE DATOS/PANDAS/emisiones_CO2.xlsx'

In [ ]:
datos_co2 = pd.read_excel(archivo)

In [ ]:
datos_co2.head()

País ISO 3166-1 alpha-3   Año  Total  Carbón  Aceite  Gas  Cemento  \
0  Afganistán                AFG  1750    0.0     NaN     NaN  NaN      NaN   
1  Afganistán                AFG  1751    0.0     NaN     NaN  NaN      NaN   
2  Afganistán                AFG  1752    0.0     NaN     NaN  NaN      NaN   
3  Afganistán                AFG  1753    0.0     NaN     NaN  NaN      NaN   
4  Afganistán                AFG  1754    0.0     NaN     NaN  NaN      NaN   

   Quema  Otros  Per Capita  
0    NaN    NaN         NaN  
1    NaN    NaN         NaN  
2    NaN    NaN         NaN  
3    NaN    NaN         NaN  
4    NaN    NaN         NaN

In [ ]:
pd.ExcelFile(archivo).sheet_names #muestra las pestañas que contiene el archivo

['emisiones_C02', 'emisiones_percapita', 'fuentes']

## Parametros de la funcion read_excel
Documentacion: https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html

In [ ]:
percapita = pd.read_excel(archivo, sheet_name='emisiones_percapita')

In [ ]:
percapita.tail() #head() sample()

País ISO 3166-1 alpha-3   Año      Total     Carbón     Aceite  \
63099  Global                WLD  2017  4749682.0  1908857.0  1610910.0   
63100  Global                WLD  2018  4792753.0  1919213.0  1596350.0   
63101  Global                WLD  2019  4775633.0  1896468.0  1589920.0   
63102  Global                WLD  2020  4497423.0  1807760.0  1427353.0   
63103  Global                WLD  2021  4693699.0  1893923.0  1496614.0   

             Gas   Cemento    Quema    Otros  
63099   940144.0  198416.0  51579.0  39776.0  
63100   979965.0  204225.0  53634.0  39366.0  
63101   984878.0  208309.0  56569.0  39490.0  
63102   963695.0  208844.0  51981.0  37789.0  
63103  1001585.0  211472.0  52663.0  37443.0

In [ ]:
fuentes = pd.read_excel(archivo, sheet_name='fuentes')

In [ ]:
fuentes.sample(5)

País ISO 3166-1 alpha-3   Año       Total      Carbón      Aceite  \
16095     Egipto                EGY  1797      [NONE]      [NONE]      [NONE]   
10123       Chad                TCD  1809      [NONE]      [NONE]      [NONE]   
3209   Australia                AUS  1967  CDIAC 2022  CDIAC 2022  CDIAC 2022   
35193  Martinica                MTQ  1855      [NONE]      [NONE]      [NONE]   
17099    Eritrea                ERI  1985      [NONE]      [NONE]      [NONE]   

              Gas        Cemento       Quema   Otros  \
16095      [NONE]         [NONE]      [NONE]  [NONE]   
10123      [NONE]         [NONE]      [NONE]  [NONE]   
3209   CDIAC 2022  Andrew cement  CDIAC 2022  [NONE]   
35193      [NONE]  Andrew cement      [NONE]  [NONE]   
17099      [NONE]         [NONE]      [NONE]  [NONE]   

                         Per Capita  
16095                        [NONE]  
10123                        [NONE]  
3209   CDIAC 2022 and UN population  
35193                        [NONE]  
17099                 UN population

In [ ]:
intervalo = pd.read_excel(archivo, sheet_name='emisiones_C02', usecols='A:D') ##SELECCIONADO LAS PRIMERAS 4 COLUMANS

In [ ]:
intervalo

País ISO 3166-1 alpha-3   Año         Total
0      Afganistán                AFG  1750  0.000000e+00
1      Afganistán                AFG  1751  0.000000e+00
2      Afganistán                AFG  1752  0.000000e+00
3      Afganistán                AFG  1753  0.000000e+00
4      Afganistán                AFG  1754  0.000000e+00
...           ...                ...   ...           ...
63099      Global                WLD  2017  3.609674e+10
63100      Global                WLD  2018  3.682651e+10
63101      Global                WLD  2019  3.708256e+10
63102      Global                WLD  2020  3.526409e+10
63103      Global                WLD  2021  3.712385e+10

[63104 rows x 4 columns]

In [ ]:
intervalo_2 = pd.read_excel(archivo, sheet_name='emisiones_C02', usecols='A:D', nrows=5) ##SELECCIONADO LAS PRIMERAS 4 COLUMANS y n filas

In [ ]:
intervalo_2

País ISO 3166-1 alpha-3   Año  Total
0  Afganistán                AFG  1750      0
1  Afganistán                AFG  1751      0
2  Afganistán                AFG  1752      0
3  Afganistán                AFG  1753      0
4  Afganistán                AFG  1754      0

##Escribiendo archivos Excel

In [ ]:
intervalo.to_excel('CO2_Percapita.xlsx', index=False)

In [ ]:
pd.read_excel('CO2_Percapita.xlsx')

País ISO 3166-1 alpha-3   Año         Total
0      Afganistán                AFG  1750  0.000000e+00
1      Afganistán                AFG  1751  0.000000e+00
2      Afganistán                AFG  1752  0.000000e+00
3      Afganistán                AFG  1753  0.000000e+00
4      Afganistán                AFG  1754  0.000000e+00
...           ...                ...   ...           ...
63099      Global                WLD  2017  3.609674e+10
63100      Global                WLD  2018  3.682651e+10
63101      Global                WLD  2019  3.708256e+10
63102      Global                WLD  2020  3.526409e+10
63103      Global                WLD  2021  3.712385e+10

[63104 rows x 4 columns]

##Leyendo datos de Google Sheets

link: https://docs.google.com/spreadsheets/d/1VbQ0LPeNZtkvVRHiPofGhKj-sOnZBA_c/edit?usp=sharing&ouid=102556269773568554773&rtpof=true&sd=true

In [ ]:
sheet_id = '1VbQ0LPeNZtkvVRHiPofGhKj-sOnZBA_c'
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet' ##/gviz/ formato de salida tqx=out:csv para leer &sheet, parametrizando link


In [ ]:
datos_co2_sheets = pd.read_csv(url)

In [ ]:
datos_co2_sheets.head()

País ISO 3166-1 alpha-3   Año Total Carbón Aceite  Gas Cemento Quema  \
0  Afganistán                AFG  1750     0    NaN    NaN  NaN     NaN   NaN   
1  Afganistán                AFG  1751     0    NaN    NaN  NaN     NaN   NaN   
2  Afganistán                AFG  1752     0    NaN    NaN  NaN     NaN   NaN   
3  Afganistán                AFG  1753     0    NaN    NaN  NaN     NaN   NaN   
4  Afganistán                AFG  1754     0    NaN    NaN  NaN     NaN   NaN   

  Otros Per Capita  
0   NaN        NaN  
1   NaN        NaN  
2   NaN        NaN  
3   NaN        NaN  
4   NaN        NaN

In [ ]:
sheet_id = '1VbQ0LPeNZtkvVRHiPofGhKj-sOnZBA_c'
sheet_name = 'emisiones_percapita'
url_percapita = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}' ##/gviz/ formato de salida tqx=out:csv para leer &sheet, parametrizando link


In [ ]:
percapita_sheets = pd.read_csv(url_percapita)

In [ ]:
percapita_sheets

País ISO 3166-1 alpha-3   Año      Total     Carbón     Aceite  \
0      Afganistán                AFG  1750        NaN        NaN        NaN   
1      Afganistán                AFG  1751        NaN        NaN        NaN   
2      Afganistán                AFG  1752        NaN        NaN        NaN   
3      Afganistán                AFG  1753        NaN        NaN        NaN   
4      Afganistán                AFG  1754        NaN        NaN        NaN   
...           ...                ...   ...        ...        ...        ...   
63099      Global                WLD  2017  4.749.682  1.908.857  1.610.910   
63100      Global                WLD  2018  4.792.753  1.919.213  1.596.350   
63101      Global                WLD  2019  4.775.633  1.896.468  1.589.920   
63102      Global                WLD  2020  4.497.423  1.807.760  1.427.353   
63103      Global                WLD  2021  4.693.699  1.893.923  1.496.614   

             Gas  Cemento   Quema   Otros  
0            NaN      NaN     NaN     NaN  
1            NaN      NaN     NaN     NaN  
2            NaN      NaN     NaN     NaN  
3            NaN      NaN     NaN     NaN  
4            NaN      NaN     NaN     NaN  
...          ...      ...     ...     ...  
63099    940.144  198.416  51.579  39.776  
63100    979.965  204.225  53.634  39.366  
63101    984.878  208.309  56.569  39.490  
63102    963.695  208.844  51.981  37.789  
63103  1.001.585  211.472  52.663  37.443  

[63104 rows x 10 columns]

In [ ]:
sheet_id = '1VbQ0LPeNZtkvVRHiPofGhKj-sOnZBA_c'
sheet_name = 'fuentes'
url_fuentes = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}' ##/gviz/ formato de salida tqx=out:csv para leer &sheet, parametrizando link


In [ ]:
fuentes_sheets = pd.read_csv(url_fuentes)

In [ ]:
fuentes_sheets.head()

País ISO 3166-1 alpha-3   Año   Total  Carbón  Aceite     Gas  \
0  Afganistán                AFG  1750  [NONE]  [NONE]  [NONE]  [NONE]   
1  Afganistán                AFG  1751  [NONE]  [NONE]  [NONE]  [NONE]   
2  Afganistán                AFG  1752  [NONE]  [NONE]  [NONE]  [NONE]   
3  Afganistán                AFG  1753  [NONE]  [NONE]  [NONE]  [NONE]   
4  Afganistán                AFG  1754  [NONE]  [NONE]  [NONE]  [NONE]   

  Cemento   Quema   Otros Per Capita  
0  [NONE]  [NONE]  [NONE]     [NONE]  
1  [NONE]  [NONE]  [NONE]     [NONE]  
2  [NONE]  [NONE]  [NONE]     [NONE]  
3  [NONE]  [NONE]  [NONE]     [NONE]  
4  [NONE]  [NONE]  [NONE]     [NONE]

#Aula 3 - Leyendo archivos JSON

## Importando archivos JSON

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd

In [ ]:
pacientes = "/content/drive/MyDrive/CIENCIA DE DATOS/PANDAS/pacientes.json"
pacientes2 = "/content/drive/MyDrive/CIENCIA DE DATOS/PANDAS/pacientes_2.json"

In [ ]:
datos_pacientes = pd.read_json(pacientes)

In [ ]:
datos_pacientes

ID_paciente Enfermedad_corazon    IMC Fumador Consumo_alcohol AVC  \
0              0                 No  16.60      Sí              No  No   
1              1                 No  20.34      No              No  Sí   
2              2                 No  26.58      Sí              No  No   
3              3                 No  24.21      No              No  No   
4              4                 No  23.71      No              No  No   
..           ...                ...    ...     ...             ...  ..   
995          995                 No  28.29      Sí              No  No   
996          996                 No  25.69      Sí              No  No   
997          997                 Sí  26.99      No              No  No   
998          998                 No  44.29      No              No  No   
999          999                 No  25.83      No              No  No   

     Salud_fisica  Salud_mental Dificultad_caminar Sexo_biologico Rango_edad  \
0               3            30                 No       Femenino      55-59   
1               0             0                 No       Femenino     80 ó +   
2              20            30                 No      Masculino      65-69   
3               0             0                 No       Femenino      75-79   
4              28             0                 Sí       Femenino      40-44   
..            ...           ...                ...            ...        ...   
995            10            20                 No       Femenino      65-69   
996             0             0                 No       Femenino      75-79   
997             1             0                 No      Masculino      70-74   
998            30             0                 Sí       Femenino      70-74   
999             0             0                 No      Masculino      70-74   

       Raza Diabetes Actividad_fisica Salud_general  Horas_sueño Asma  \
0    Blanca       Sí               Sí     Muy buena            5   Sí   
1    Blanca       No               Sí     Muy buena            7   No   
2    Blanca       Sí               Sí     Razonable            8   Sí   
3    Blanca       No               No         Buena            6   No   
4    Blanca       No               Sí     Muy buena            8   No   
..      ...      ...              ...           ...          ...  ...   
995   Negra       Sí               Sí     Razonable            8   No   
996  Blanca       No               Sí     Excelente            8   No   
997  Blanca       No               Sí     Muy buena            8   No   
998  Blanca       Sí               No         Buena            6   Sí   
999   Negra       Sí               No     Excelente            7   No   

    Enfermedad_renal Cancer_piel  
0                 No          Sí  
1                 No          No  
2                 No          No  
3                 No          Sí  
4                 No          No  
..               ...         ...  
995               No          No  
996               No          No  
997               No          No  
998               No          No  
999               No          No  

[1000 rows x 19 columns]

In [ ]:
datos_pacientes_2 = pd.read_json(pacientes2)

In [ ]:
datos_pacientes_2

Investigación   Año  \
0  Indicadores clave de enfermedades cardíacas  2020   
1  Indicadores clave de enfermedades cardíacas  2020   
2  Indicadores clave de enfermedades cardíacas  2020   

                                           Pacientes  
0  {'ID': '01', 'Rango_edad': '55-59', 'Sexo_biol...  
1  {'ID': '02', 'Rango_edad': '80 ó +', 'Sexo_bio...  
2  {'ID': '03', 'Rango_edad': '65-69', 'Sexo_biol...

##Normalizando archivos JSON


La normalización de datos es un proceso importante en la ciencia de datos que tiene como objetivo organizar y estandarizar datos para facilitar el análisis y la comparación entre ellos. Cuando se trata de datos en formato JSON (JavaScript Object Notation - Notación de objetos JavaScript), es común que estén anidados, lo que puede dificultar su análisis y manipulación.

La biblioteca Pandas cuenta con una función llamada json_normalize() que permite la transformación de datos a formato tabular, facilitando la visualización y análisis de las informaciones.

Normalizando un JSON simple

A continuación tenemos una variable llamada datos y dentro de ella hay un objeto JSON con tres llaves y sus respectivos valores:


```
datos = {'Análisis': 'Principales indicadores de enfermedad cardíaca', 'Año': 2020, 'Numero_Pacientes':3}
```
Para normalizar esta variable, podemos pasarla dentro de la función json_normalize y analizar el DataFrame obtenido:


```
df = pd.json_normalize(datos)
df
```
Normalizando un JSON con múltiples niveles

Hay situaciones en las que el archivo JSON puede contener más de un objeto, como es el caso del siguiente ejemplo, en el que tenemos una lista, almacenada en la variable json_lista, que contiene dos objetos JSON:



```
json_lista = [
    { 'ID': '01', 'Intervalo_edad': '55-59', 'Sexo_biologico': 'femenino'},
    { 'ID': '02', 'Intervalo_edad': '80 ó +', 'Sexo_biologico': 'femenino'}
]
```
Para normalizar esta lista podemos aplicar la función json_normalize:


```
pd.json_normalize(json_lista)
```

Bueno, notamos que la función json_normalize() funciona muy bien en las situaciones anteriores, pero ¿qué pasa en otras situaciones?

Datos como un diccionario

Iniciemos observando la normalización cuando los datos son un diccionario. Tenemos un diccionario almacenado en la variable json_obj. Observe que en la llave “Salud” tenemos otro diccionario:


```
json_obj = {
    'ID': '01',
    'Intervalo_edad': '55-59',
    'Sexo_biologico': 'Femenino',
    'Salud': {'Dificultad_caminar': 'No',
              'Actividad_fisica': 'Sí',
              'IMC': 16.6,
              'Enfermedad_cardiaca': 'No',
          }
      }
```
Haciendo la normalización:


```
pd.json_normalize(json_obj)
```





l DataFrame generado tiene una columna para cada información contenida en el diccionario que estaba en “Salud”. Las columnas creadas tienen el prefijo “Salud.”, ya que la información proviene de esa misma llave.

Datos como una lista de diccionarios.

Ahora tenemos una lista de diccionarios almacenados en la variable json_list:


```
json_list = [
    {
    'ID': '01',
    'Intervalo_edad': '55-59',
    'Sexo_biologico': 'Femenino',
    'Salud': {'Dificultad_caminar': 'No',
              'Actividad_fisica': 'Sí',
              'IMC': 16.6,
              'Enfermedad_cardiaca': 'No',
          }
      },
      {
          'ID': '02',
          'Intervalo_edad': '80 ó +',
          'Sexo_biologico': 'Femenino',
          'Salud': {'Dificultad_caminar': 'No',
                    'Actividad_fisica': 'Sí',
                    'IMC': 20.34,
                    'Enfermedad_cardiaca': 'Sí'}
       }
       ]
```
Haciendo la normalización:


```
pd.json_normalize(json_list)
```

Podemos ver que todos los valores anidados dentro de cada registro de la lista se han convertido en columnas separadas. ¿Qué pasa con los datos que normalizamos en el video anterior? ¿Recuerdas cómo su normalización se hizo de otra manera?

Resumiendo, vamos a copiar los datos del archivo paciente_2.json y vamos a guardarlos en una variable llamada datos_dict.


```
datos_dict = {
  "Investigación": "Indicadores clave de enfermedades cardíacas",
  "Año": 2020,
  "Pacientes": [
    {
     "ID": "01",
      "Rango_edad": "55-59",
      "Sexo_biologico": "Mujer",
      "Raza": "Blanca",
      "IMC": 16.6,
      "Fumador": "Sí",
      "Consumo_alcohol": "No",
      "Salud_física": 3,
      "Salud_mental": 30,
      "Dificultad_caminar": "No",
      "Actividad_física": "Sí",
      "Salud_general": "Muy buena",
      "Horas_sueño": 5,
      "Problemas_salud": [
        "Diabetes",
        "Asma",
        "Cancer_piel"
      ]
    },
    {
      "ID": "02",
      "Rango_edad": "80 ó +",
      "Sexo_biologico": "Mujer",
      "Raza": "Blanca",
      "IMC": 20.34,
      "Fumador": "No",
      "Consumo_alcohol": "No",
      "Salud_física": 0,
      "Salud_mental": 0,
      "Dificultad_caminar": "No",
      "Actividad_física": "Sí",
      "Salud_general": "Muy buena",
      "Horas_sueño": 7,
      "Problemas_salud": [
        "AVC"
      ]
    },
    {
      "ID": "03",
      "Rango_edad": "65-69",
      "Sexo_biologico": "Masculino",
      "Raza": "Blanca",
      "IMC": 26.58,
      "Fumador": "Sí",
      "Consumo_alcohol": "No",
      "Salud_física": 20,
      "Salud_mental": 30,
      "Dificultad_caminar": "No",
      "Actividad_física": "Sí",
      "Salud_general": "Muy buena",
      "Horas_sueño": 8,
      "Problemas_salud": [
        "Diabetes",
        "Asma"
      ]
    }
  ]
}
```
Si intentamos normalizar estos datos:

```
pd.json_normalize(datos_dict)
```
Podemos observar que nuestra lista anidada está colocada en una única columna Pacientes. Entonces, usaremos el siguiente código para normalizar los datos, especificando qué columna está anidada:
```
pd.json_normalize(datos_dict['Pacientes'])
```
También podemos hacer esto usando el parámetro record_path como ['Pacientes']. Este parámetro se utiliza en la función pd.json_normalize() para especificar la ruta a los registros que deben ser normalizados en un DataFrame separado:
```
pd.json_normalize(datos_dict, record_path=['Pacientes'])
```

El resultado parece excelente, pero no incluye las columnas "Investigación" y "Año". Para incluirlas, podemos usar el parámetro meta para especificar otras columnas que queramos en el DataFrame.

```
pd.json_normalize(
    datos_dict,
    record_path =['Pacientes'],
    meta=[‘Investigación’, 'Año']
)
```

Importante: En clase nosotros realizamos la normalización en un archivo con formato JSON. Sin embargo, la función json_normalize() sólo acepta un diccionario o una lista de diccionarios. Por esto, en el video se utilizó la estrategia de usar el código: pd.json_normalize(datos_pacientes_2['Pacientes']). Sin embargo, si intentamos utilizar parámetros de la función json_normalize en un archivo JSON, pueden surgir errores. Para solucionar esto, necesitamos importar el módulo json y leer los archivos según el siguiente código:

```
#Importando la biblioteca Pandas
import pandas as pd

#Importando el módulo JSON
import json

#Leyendo el archivo json usando el módulo Python JSON
with open('pacientes_2.json','r') as f:
    datos = json.loads(f.read())

#Normalizando los datos con los parámetros record_path y meta
pd.json_normalize(datos, record_path='Pacientes', meta=['Investigación', 'Año'])
```

In [ ]:
df_normalizado = pd.json_normalize(datos_pacientes_2['Pacientes'])

In [ ]:
df_normalizado

ID Rango_edad Sexo_biologico    Raza    IMC Fumador Consumo_alcohol  \
0  01      55-59          Mujer  Blanca  16.60      Sí              No   
1  02     80 ó +          Mujer  Blanca  20.34      No              No   
2  03      65-69      Masculino  Blanca  26.58      Sí              No   

   Salud_física  Salud_mental Dificultad_caminar Actividad_física  \
0             3            30                 No               Sí   
1             0             0                 No               Sí   
2            20            30                 No               Sí   

  Salud_general  Horas_sueño                Problemas_salud  
0     Muy buena            5  [Diabetes, Asma, Cancer_piel]  
1     Muy buena            7                          [AVC]  
2     Muy buena            8               [Diabetes, Asma]

##Escribiendo archivos JSON

In [ ]:
df_normalizado.to_json('pacientes_normalizados.json')

In [ ]:
pd.read_json('pacientes_normalizados.json')

ID Rango_edad Sexo_biologico    Raza    IMC Fumador Consumo_alcohol  \
0   1      55-59          Mujer  Blanca  16.60      Sí              No   
1   2     80 ó +          Mujer  Blanca  20.34      No              No   
2   3      65-69      Masculino  Blanca  26.58      Sí              No   

   Salud_física  Salud_mental Dificultad_caminar Actividad_física  \
0             3            30                 No               Sí   
1             0             0                 No               Sí   
2            20            30                 No               Sí   

  Salud_general  Horas_sueño                Problemas_salud  
0     Muy buena            5  [Diabetes, Asma, Cancer_piel]  
1     Muy buena            7                          [AVC]  
2     Muy buena            8               [Diabetes, Asma]

##Situacion-problema
“Una empresa de alimentos saludables tiene problemas con la popularidad de sus productos. A pesar de ofrecer opciones saludables, muchos clientes se muestran reacios a comprar los productos debido a la falta de información sobre los valores nutricionales de las frutas que se utilizan en la producción de alimentos”.

Ante esta situación podemos acceder a una API llamada [Fruitvice](https://fruityvice.com/#3) para recopilar información detallada sobre los valores nutricionales de las frutas que se utilizan en los productos. Con esta información, la empresa podrá actualizar sus empaques y materiales de marketing para resaltar los valores nutricionales de las frutas y así atraer más clientes que buscan opciones saludables. Además, la empresa puede utilizar la información para desarrollar nuevos productos que satisfagan aún más las necesidades nutricionales de su clientela.

Una forma común de acceder a las API es a través de la biblioteca [requests](https://pypi.org/project/requests/). Para eso, también es necesario importar el módulo json:
(En GoogleColab: !pip install requests para poder importar)

In [ ]:
!pip install requests

In [ ]:
import requests
import json

In [ ]:
datos_frutas = requests.get('https://fruityvice.com/api/fruit/all')

Conseguimos recuperar los resultados utilizando la función json.loads(). Para ello es necesario pasar la variable datos_frutas, previamente creada con el atributo text que devuelve el contenido de la respuesta.

In [ ]:
resultado = json.loads(datos_frutas.text)

In [ ]:
pd.DataFrame(resultado)


name   id           family             order         genus  \
0            Persimmon   52        Ebenaceae           Rosales     Diospyros   
1           Strawberry    3         Rosaceae           Rosales      Fragaria   
2               Banana    1         Musaceae      Zingiberales          Musa   
3               Tomato    5       Solanaceae         Solanales       Solanum   
4                 Pear    4         Rosaceae           Rosales         Pyrus   
5               Durian   60        Malvaceae          Malvales         Durio   
6           Blackberry   64         Rosaceae           Rosales         Rubus   
7          Lingonberry   65        Ericaceae          Ericales     Vaccinium   
8                 Kiwi   66    Actinidiaceae  Struthioniformes       Apteryx   
9               Lychee   67      Sapindaceae        Sapindales        Litchi   
10           Pineapple   10     Bromeliaceae            Poales        Ananas   
11                 Fig   68         Moraceae           Rosales         Ficus   
12          Gooseberry   69  Grossulariaceae      Saxifragales         Ribes   
13        Passionfruit   70   Passifloraceae      Malpighiales    Passiflora   
14                Plum   71         Rosaceae           Rosales        Prunus   
15              Orange    2         Rutaceae        Sapindales        Citrus   
16          GreenApple   72         Rosaceae           Rosales         Malus   
17           Raspberry   23         Rosaceae           Rosales         Rubus   
18          Watermelon   25    Cucurbitaceae      Cucurbitales     Citrullus   
19               Lemon   26         Rutaceae        Sapindales        Citrus   
20               Mango   27    Anacardiaceae        Sapindales     Mangifera   
21           Blueberry   33         Rosaceae           Rosales      Fragaria   
22               Apple    6         Rosaceae           Rosales         Malus   
23               Guava   37        Myrtaceae          Myrtales       Psidium   
24             Apricot   35         Rosaceae           Rosales        Prunus   
25               Melon   41    Cucurbitaceae     Cucurbitaceae       Cucumis   
26           Tangerine   77         Rutaceae        Sapindales        Citrus   
27            Pitahaya   78        Cactaceae    Caryophyllales     Cactaceae   
28                Lime   44         Rutaceae        Sapindales        Citrus   
29         Pomegranate   79       Lythraceae          Myrtales        Punica   
30         Dragonfruit   80        Cactaceae    Caryophyllales  Selenicereus   
31               Grape   81         Vitaceae           Vitales         Vitis   
32               Morus   82         Moraceae           Rosales         Morus   
33              Feijoa   76        Myrtaceae        Myrtoideae    Sellowiana   
34             Avocado   84        Lauraceae          Laurales        Persea   
35           Kiwifruit   85    Actinidiaceae          Ericales     Actinidia   
36           Cranberry   87        Ericaceae          Ericales     Vaccinium   
37              Cherry    9         Rosaceae           Rosales        Prunus   
38               Peach   86         Rosaceae           Rosales        Prunus   
39           Jackfruit   94         Moraceae           Rosales    Artocarpus   
40        Horned Melon   95    Cucurbitaceae      Cucurbitales       Cucumis   
41            Hazelnut   96       Betulaceae           Fagales       Corylus   
42              Pomelo   98         Rutaceae        Sapindales        Citrus   
43          Mangosteen   99       Clusiaceae      Malpighiales      Garcinia   
44             Pumpkin  100    Cucurbitaceae      Cucurbitales     Cucurbita   
45  Japanese Persimmon  101        Ebenaceae          Ericales     Diospyros   
46              Papaya   42       Caricaceae       Brassicales        Carica   
47              Annona  103       Annonaceae           Rosales       Annonas   
48   Ceylon Gooseberry  104       Salicaceae      Malpighiales      Dovyalis   

                 

In [ ]:
import pandas as pd
datos_frutas_normalizado = pd.json_normalize(resultado)

In [ ]:
datos_frutas_normalizado

name   id           family             order         genus  \
0            Persimmon   52        Ebenaceae           Rosales     Diospyros   
1           Strawberry    3         Rosaceae           Rosales      Fragaria   
2               Banana    1         Musaceae      Zingiberales          Musa   
3               Tomato    5       Solanaceae         Solanales       Solanum   
4                 Pear    4         Rosaceae           Rosales         Pyrus   
5               Durian   60        Malvaceae          Malvales         Durio   
6           Blackberry   64         Rosaceae           Rosales         Rubus   
7          Lingonberry   65        Ericaceae          Ericales     Vaccinium   
8                 Kiwi   66    Actinidiaceae  Struthioniformes       Apteryx   
9               Lychee   67      Sapindaceae        Sapindales        Litchi   
10           Pineapple   10     Bromeliaceae            Poales        Ananas   
11                 Fig   68         Moraceae           Rosales         Ficus   
12          Gooseberry   69  Grossulariaceae      Saxifragales         Ribes   
13        Passionfruit   70   Passifloraceae      Malpighiales    Passiflora   
14                Plum   71         Rosaceae           Rosales        Prunus   
15              Orange    2         Rutaceae        Sapindales        Citrus   
16          GreenApple   72         Rosaceae           Rosales         Malus   
17           Raspberry   23         Rosaceae           Rosales         Rubus   
18          Watermelon   25    Cucurbitaceae      Cucurbitales     Citrullus   
19               Lemon   26         Rutaceae        Sapindales        Citrus   
20               Mango   27    Anacardiaceae        Sapindales     Mangifera   
21           Blueberry   33         Rosaceae           Rosales      Fragaria   
22               Apple    6         Rosaceae           Rosales         Malus   
23               Guava   37        Myrtaceae          Myrtales       Psidium   
24             Apricot   35         Rosaceae           Rosales        Prunus   
25               Melon   41    Cucurbitaceae     Cucurbitaceae       Cucumis   
26           Tangerine   77         Rutaceae        Sapindales        Citrus   
27            Pitahaya   78        Cactaceae    Caryophyllales     Cactaceae   
28                Lime   44         Rutaceae        Sapindales        Citrus   
29         Pomegranate   79       Lythraceae          Myrtales        Punica   
30         Dragonfruit   80        Cactaceae    Caryophyllales  Selenicereus   
31               Grape   81         Vitaceae           Vitales         Vitis   
32               Morus   82         Moraceae           Rosales         Morus   
33              Feijoa   76        Myrtaceae        Myrtoideae    Sellowiana   
34             Avocado   84        Lauraceae          Laurales        Persea   
35           Kiwifruit   85    Actinidiaceae          Ericales     Actinidia   
36           Cranberry   87        Ericaceae          Ericales     Vaccinium   
37              Cherry    9         Rosaceae           Rosales        Prunus   
38               Peach   86         Rosaceae           Rosales        Prunus   
39           Jackfruit   94         Moraceae           Rosales    Artocarpus   
40        Horned Melon   95    Cucurbitaceae      Cucurbitales       Cucumis   
41            Hazelnut   96       Betulaceae           Fagales       Corylus   
42              Pomelo   98         Rutaceae        Sapindales        Citrus   
43          Mangosteen   99       Clusiaceae      Malpighiales      Garcinia   
44             Pumpkin  100    Cucurbitaceae      Cucurbitales     Cucurbita   
45  Japanese Persimmon  101        Ebenaceae          Ericales     Diospyros   
46              Papaya   42       Caricaceae       Brassicales        Carica   
47              Annona  103       Annonaceae           Rosales       Annonas   
48   Ceylon Gooseberry  104       Salicaceae      Malpighiales      Dovyalis   

    nutritions.ca

#Aula 4 - Leyendo páginas en HTML e XML

##Importando páginas web

In [ ]:
import pandas as pd

In [ ]:
pagina = "/content/drive/MyDrive/CIENCIA DE DATOS/PANDAS/pagina/AFI's 100 Years...100 Movies - Wikipedia.html"

In [ ]:
datos_html = pd.read_html(pagina)

In [ ]:
datos_html

[       0                      1
 0   1998             100 Movies
 1   1999              100 Stars
 2   2000             100 Laughs
 3   2001            100 Thrills
 4   2002           100 Passions
 5   2003  100 Heroes & Villains
 6   2004              100 Songs
 7   2005       100 Movie Quotes
 8   2005              25 Scores
 9   2006             100 Cheers
 10  2006            25 Musicals
 11  2007   100 Movies (Updated)
 12  2008        AFI's 10 Top 10
 13   vte                    vte,
                       Film  Release year              Director  \
 0             Citizen Kane          1941          Orson Welles   
 1               Casablanca          1942        Michael Curtiz   
 2            The Godfather          1972  Francis Ford Coppola   
 3       Gone with the Wind          1939        Victor Fleming   
 4       Lawrence of Arabia          1962            David Lean   
 ..                     ...           ...                   ...   
 118        Sophie's Choice        

In [ ]:
type(datos_html)

list

In [ ]:
len(datos_html)

2

In [ ]:
top_peliculas = datos_html[1]

In [ ]:
top_peliculas

Film  Release year              Director  \
0             Citizen Kane          1941          Orson Welles   
1               Casablanca          1942        Michael Curtiz   
2            The Godfather          1972  Francis Ford Coppola   
3       Gone with the Wind          1939        Victor Fleming   
4       Lawrence of Arabia          1962            David Lean   
..                     ...           ...                   ...   
118        Sophie's Choice          1982        Alan J. Pakula   
119  The Last Picture Show          1971     Peter Bogdanovich   
120     Do the Right Thing          1989             Spike Lee   
121           Blade Runner          1982          Ridley Scott   
122              Toy Story          1995         John Lasseter   

                              Production companies 1998 Rank 2007 Rank  
0                               RKO Radio Pictures         1         1  
1                            Warner Bros. Pictures         2         3  
2           Paramount Pictures, Alfran Productions         3         2  
3                  Selznick International Pictures         4         6  
4                                 Horizon Pictures         5         7  
..                                             ...       ...       ...  
118                              ITC Entertainment         -        91  
119                                BBS Productions         -        95  
120                  40 Acres and a Mule Filmworks         -        96  
121                The Ladd Company, Shaw Brothers         -        97  
122  Walt Disney Pictures, Pixar Animation Studios         -        99  

[123 rows x 6 columns]

##Escribiendo archivos HTML

In [ ]:
top_peliculas.to_html('top_peliculas.html')

In [ ]:
pd.read_html('top_peliculas.html')

[     Unnamed: 0                   Film  Release year              Director  \
 0             0           Citizen Kane          1941          Orson Welles   
 1             1             Casablanca          1942        Michael Curtiz   
 2             2          The Godfather          1972  Francis Ford Coppola   
 3             3     Gone with the Wind          1939        Victor Fleming   
 4             4     Lawrence of Arabia          1962            David Lean   
 ..          ...                    ...           ...                   ...   
 118         118        Sophie's Choice          1982        Alan J. Pakula   
 119         119  The Last Picture Show          1971     Peter Bogdanovich   
 120         120     Do the Right Thing          1989             Spike Lee   
 121         121           Blade Runner          1982          Ridley Scott   
 122         122              Toy Story          1995         John Lasseter   
 
                               Production companie

In [ ]:
top_peliculas.to_csv('top_peliculas_1988.csv', index=False)

In [ ]:
datos = pd.read_csv('top_peliculas_1988.csv')
datos.head()

Film  Release year              Director  \
0        Citizen Kane          1941          Orson Welles   
1          Casablanca          1942        Michael Curtiz   
2       The Godfather          1972  Francis Ford Coppola   
3  Gone with the Wind          1939        Victor Fleming   
4  Lawrence of Arabia          1962            David Lean   

                     Production companies 1998 Rank 2007 Rank  
0                      RKO Radio Pictures         1         1  
1                   Warner Bros. Pictures         2         3  
2  Paramount Pictures, Alfran Productions         3         2  
3         Selznick International Pictures         4         6  
4                        Horizon Pictures         5         7

##Leyendo/escribiendo archivos XLM

In [18]:
import pandas as pd

In [19]:
imdb_top_1000_xlm = '/content/drive/MyDrive/CIENCIA DE DATOS/PANDAS/1980-aula4/data/imdb_top_1000.xml'

In [21]:
datos_imdb = pd.read_xml(imdb_top_1000_xlm)

In [22]:
datos_imdb.head(3)

index                                        Poster_Link  \
0      0  https://m.media-amazon.com/images/M/MV5BMDFkYT...   
1      1  https://m.media-amazon.com/images/M/MV5BM2MyNj...   
2      2  https://m.media-amazon.com/images/M/MV5BMTMxNT...   

               Series_Title Released_Year Certificate  Runtime  \
0  The Shawshank Redemption          1994           A  142 min   
1             The Godfather          1972           A  175 min   
2           The Dark Knight          2008          UA  152 min   

                  Genre  IMDB_Rating  \
0                 Drama          9.3   
1          Crime, Drama          9.2   
2  Action, Crime, Drama          9.0   

                                            Overview  Meta_score  \
0  Two imprisoned men bond over a number of years...        80.0   
1  An organized crime dynasty's aging patriarch t...       100.0   
2  When the menace known as the Joker wreaks havo...        84.0   

               Director           Star1           Star2          Star3  \
0        Frank Darabont     Tim Robbins  Morgan Freeman     Bob Gunton   
1  Francis Ford Coppola   Marlon Brando       Al Pacino     James Caan   
2     Christopher Nolan  Christian Bale    Heath Ledger  Aaron Eckhart   

            Star4  No_of_Votes        Gross  
0  William Sadler      2343110   28,341,469  
1    Diane Keaton      1620367  134,966,411  
2   Michael Caine      2303232  534,858,444

In [23]:
datos_imdb.to_xml('peliculas_imdb.xml', index=False)

##Desafio 04.Leyendo páginas en HTML en XML

In [24]:
pd.read_html('https://es.wikipedia.org/wiki/Anexo:Pa%C3%ADses_y_territorios_dependientes_por_poblaci%C3%B3n')[0]

HTTPError: HTTP Error 403: Forbidden

In [26]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = 'https://es.wikipedia.org/wiki/Anexo:Pa%C3%ADses_y_territorios_dependientes_por_poblaci%C3%B3n'

try:
    # Make a GET request to the Wikipedia page with a user-agent header to mimic a browser
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
    response = requests.get(url, headers=headers)
    response.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)

    # Parse the HTML content using BeautifulSoup
    soup = BeautifulSoup(response.text, 'html.parser')

    # Try to read tables from the parsed HTML content
    tables = pd.read_html(str(soup))

    # Display the first table found
    if tables:
        print(f"Se encontraron {len(tables)} tablas en la página.")
        display(tables[0])
    else:
        print("No se encontraron tablas en la página.")

except requests.exceptions.RequestException as e:
    print(f"Error al acceder a la página web: {e}")
except Exception as e:
    print(f"Ocurrió un error inesperado: {e}")

/tmp/ipython-input-770055897.py:17: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(str(soup))


Se encontraron 7 tablas en la página.


N.º                   País (o territorio dependiente)  \
0      1                                             India   
1      2                                        China[12]​   
2      3                                    Estados Unidos   
3      4                                         Indonesia   
4      5                                          Pakistán   
..   ...                                               ...   
241  242                           Islas Cocos (Australia)   
242  243  Islas Ultramarinas Menores de los Estados Unidos   
243  244                               Islas Pitcairn (RU)   
244  NaN                                             Mundo   
245   N°                   País (o territorio dependiente)   

    Proyección exponencial de la población al 1/7/2025[7]​  \
0                                        1 417 492 000       
1                                        1 407 934 000       
2                                          342 181 000       
3                                          284 447 000       
4                                          256 204 000       
..                                                 ...       
241                                                600       
242                                                100       
243                                                 30       
244                                      8 079 659 000       
245  Proyección exponencial de la población al 1/7/...       

     Total mun- dial (%) Cambio medio anual (%)[8]​  \
0                   1754                        090   
1                   1743                       -005   
2                    424                        061   
3                    352                        107   
4                    317                        256   
..                   ...                        ...   
241                  000                        174   
242                  000                       -496   
243                  000                       -111   
244                10000                        101   
245  Total mun- dial (%)     Cambio medio anual (%)   

     Cambio absoluto anual promedio  Cambio medio abs. total anual (%)  \
0                        12 692 000                               1547   
1                        -1 390 000                                  -   
2                         2 084 000                                254   
3                         3 043 000                                371   
4                         6 567 000                                801   
..                              ...                                ...   
241                               0                                000   
242                               0                                000   
243                               0                                000   
244                      82 026 000                              10000   
245  Cambio absoluto anual promedio  Cambio medio abs. total anual (%)   

    Años para even- tual du- pli- ca- ción[9]​  \
0                                           78   
1                                            -   
2                                          114   
3                                           65   
4                                           27   
..                                         ...   
241                                         40   
242                                          -   
243                                          -   
244                                         69   
245     Años para even- tual du- pli- ca- ción   

    Censo más reciente, última estimación oficial, proyección de la ONU o reloj de población nacional  \
0                                        1 417 492 000                                                  
1                                        1 408 280 000                                                  
2                                          343 04

#Aula 5 - Leyendo banco de datos


Python ofrece varios paquetes y bibliotecas para trabajar con bases de datos, incluyendo SQLite, MySQL, PostgreSQL, Oracle, MongoDB, entre otros. Uno de los paquetes más comunes utilizados para trabajar con bases de datos relacionales en Python es el paquete sqlite3 que ofrece soporte a bases de datos SQLite. Esta base de datos es liviana e integrada, no requiere un servidor separado para ejecutarse y está instalada de forma nativa en Google Colab.

Para trabajar con esta base de datos, podemos usar SQLAlchemy, una biblioteca de mapeo objeto-relacional (ORM), que permite interactuar con bases de datos relacionales usando código Python. Proporciona una capa de abstracción que permite a los desarrolladores trabajar con objetos Python en lugar de lidiar directamente con las complejidades del lenguaje SQL (Structured Query Language - Lenguaje de consulta estructurado).

Uno de los principales beneficios de utilizar SQLAchemy es la capacidad de crear código más legible y fácil de mantener. Con SQLAlchemy, las operaciones de la base de datos se realizan utilizando métodos en objetos Python, lo que hace que el código sea más claro y menos propenso a errores.

Además, SQLAlchemy ofrece soporte a consultas complejas en bases de datos, lo que permite a los desarrolladores extraer fácilmente información relevante de grandes conjuntos de datos. Esto es especialmente útil en aplicaciones que necesitan manejar grandes cantidades de datos.

## Creando un banco de datos local

SQL (Structured Query Language - Lenguaje de consulta estructurado) es un lenguaje de consulta utilizado en bases de datos relacionales para insertar, actualizar, consultar y administrar datos.

Para hacer todo esto, existen cláusulas SQL, que son componentes fundamentales de las sentencias SQL, permitiendo especificar detalles sobre cómo se va a realizar la consulta u operación de la base de datos. Las cláusulas se utilizan para filtrar, ordenar, agrupar y limitar los resultados de la consulta.

Las sentencias SQL pueden estar compuestas por una o más cláusulas que proporcionan información adicional sobre lo que se supone que debe hacer la consulta. Las cláusulas más comunes son:

SELECT: especifica qué columnas deben seleccionarse en la consulta.
FROM: Especifica las tablas de la base de datos que se consultarán.
WHERE: Filtra los resultados de la consulta según una o más condiciones especificadas.
ORDER BY: Ordena los resultados de la consulta en orden ascendente o descendente según una o más columnas.
GROUP BY: agrupa los resultados de la consulta basados en una o más columnas.
LIMIT: limita el número de filas devueltas por los resultados de la consulta.
Tenemos un ejemplo sencillo de sintaxis SQL que utiliza el comando SELECT para consultar datos de una tabla de empleados en una base de datos:


```
SELECT nombre, apellido, salario
FROM empleados
WHERE departamento = 'ventas'
```
En esta declaración SQL, la cláusula SELECT se utiliza para especificar las columnas que desea consultar de la tabla "empleados", incluyendo "nombre", "apellido" y "salario". La cláusula FROM se utiliza para especificar la tabla que se desea consultar, que en este caso es "empleados".

La cláusula WHERE se utiliza para filtrar los resultados de la consulta según una condición específica. En este ejemplo, la condición es departamento = 'ventas', lo que significa que la consulta solo devolverá empleados que trabajan en el departamento de ventas.

En el próximo vídeo aprenderemos a utilizar algunas de estas cláusulas para realizar las primeras consultas SQL en la tabla que contiene datos de clientes de una institución financiera.


In [4]:
import sqlalchemy

In [10]:
from sqlalchemy import create_engine, MetaData, Table, inspect, text ##importando metodos

In [11]:
engine = create_engine('sqlite:///:memory:')

## Escribiendo en un banco de datos


In [12]:
import pandas as pd

In [14]:
archivo = '/content/drive/MyDrive/CIENCIA DE DATOS/PANDAS/1980-aula5/data/clientes_banco.csv'

In [16]:
datos = pd.read_csv(archivo)

In [18]:
datos.head()

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0     5008804    32    Nivel superior  Relación-estable               2   
1     5008805    32    Nivel superior  Relación-estable               2   
2     5008806    58  Nivel intermedio            Casado               2   
3     5008808    52  Nivel intermedio           Soltero               1   
4     5008809    52  Nivel intermedio           Soltero               1   

  Categoria_de_renta  Ocupacion  Años_empleado  Rendimiento_anual  \
0           Empleado       Otro             12           427500.0   
1           Empleado       Otro             12           427500.0   
2           Empleado  Seguridad              3           112500.0   
3   Business Partner     Ventas              8           270000.0   
4   Business Partner     Ventas              8           270000.0   

   Tiene_carro                  Vivienda  
0            1    Departamento alquilado  
1            1    Departamento alquilado  
2            1  Casa/Departamento propio  
3            0  Casa/Departamento propio  
4            0  Casa/Departamento propio

In [19]:
datos.to_sql('clientes', engine, index=False)

438463

In [20]:
inspector = inspect(engine) ##revisar todo el motor de engine

In [21]:
print(inspector.get_table_names()) ##mento de inspect

['clientes']


##Leyendo una consulta SQL


In [23]:
query = 'SELECT * FROM clientes WHERE Categoria_de_renta = "Empleado"'

In [24]:
empleados = pd.read_sql(sql=text(query), con = engine.connect())##convirtiendo variable de texto query a tipo text y esa variable a SQL

In [25]:
type(empleados)

pandas.core.frame.DataFrame

In [26]:
empleados

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804    32    Nivel superior  Relación-estable               2   
1          5008805    32    Nivel superior  Relación-estable               2   
2          5008806    58  Nivel intermedio            Casado               2   
3          5008815    46    Nivel superior            Casado               2   
4          5112956    46    Nivel superior            Casado               2   
...            ...   ...               ...               ...             ...   
226054     6837905    43  Nivel intermedio            Casado               3   
226055     6837906    43  Nivel intermedio            Casado               3   
226056     6839936    34  Nivel intermedio            Casado               3   
226057     6840222    43  Nivel intermedio           Soltero               1   
226058     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado                Otro             12   
2                Empleado           Seguridad              3   
3                Empleado        Contabilidad              2   
4                Empleado        Contabilidad              2   
...                   ...                 ...            ...   
226054           Empleado                Otro              7   
226055           Empleado                Otro              7   
226056           Empleado  Construcción Civil              5   
226057           Empleado  Construcción Civil              8   
226058           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                427500.0            1    Departamento alquilado  
2                112500.0            1  Casa/Departamento propio  
3                270000.0            1  Casa/Departamento propio  
4                270000.0            1  Casa/Departamento propio  
...                   ...          ...                       ...  
226054           355050.0            1  Casa/Departamento propio  
226055           355050.0            1  Casa/Departamento propio  
226056           135000.0            1  Casa/Departamento propio  
226057           103500.0            0  Casa/Departamento propio  
226058           121500.0            0  Casa/Departamento propio  

[226059 rows x 11 columns]

In [27]:
empleados.to_sql('empleados', con = engine.connect(), index=False)

226059

In [28]:
pd.read_sql_table('empleados', con=engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804    32    Nivel superior  Relación-estable               2   
1          5008805    32    Nivel superior  Relación-estable               2   
2          5008806    58  Nivel intermedio            Casado               2   
3          5008815    46    Nivel superior            Casado               2   
4          5112956    46    Nivel superior            Casado               2   
...            ...   ...               ...               ...             ...   
226054     6837905    43  Nivel intermedio            Casado               3   
226055     6837906    43  Nivel intermedio            Casado               3   
226056     6839936    34  Nivel intermedio            Casado               3   
226057     6840222    43  Nivel intermedio           Soltero               1   
226058     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado                Otro             12   
2                Empleado           Seguridad              3   
3                Empleado        Contabilidad              2   
4                Empleado        Contabilidad              2   
...                   ...                 ...            ...   
226054           Empleado                Otro              7   
226055           Empleado                Otro              7   
226056           Empleado  Construcción Civil              5   
226057           Empleado  Construcción Civil              8   
226058           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                427500.0            1    Departamento alquilado  
2                112500.0            1  Casa/Departamento propio  
3                270000.0            1  Casa/Departamento propio  
4                270000.0            1  Casa/Departamento propio  
...                   ...          ...                       ...  
226054           355050.0            1  Casa/Departamento propio  
226055           355050.0            1  Casa/Departamento propio  
226056           135000.0            1  Casa/Departamento propio  
226057           103500.0            0  Casa/Departamento propio  
226058           121500.0            0  Casa/Departamento propio  

[226059 rows x 11 columns]

In [30]:
pd.read_sql_table('empleados', con=engine.connect(), columns=['Edad', 'Años_empleado', 'Rendimiento_anual'])

Edad  Años_empleado  Rendimiento_anual
0         32             12           427500.0
1         32             12           427500.0
2         58              3           112500.0
3         46              2           270000.0
4         46              2           270000.0
...      ...            ...                ...
226054    43              7           355050.0
226055    43              7           355050.0
226056    34              5           135000.0
226057    43              8           103500.0
226058    51              3           121500.0

[226059 rows x 3 columns]

##Actualizando un banco de datos

In [31]:
query = 'SELECT * FROM clientes'

In [32]:
pd.read_sql(sql=text(query), con = engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804    32    Nivel superior  Relación-estable               2   
1          5008805    32    Nivel superior  Relación-estable               2   
2          5008806    58  Nivel intermedio            Casado               2   
3          5008808    52  Nivel intermedio           Soltero               1   
4          5008809    52  Nivel intermedio           Soltero               1   
...            ...   ...               ...               ...             ...   
438458     6840104    62  Nivel intermedio        Divorciado               1   
438459     6840222    43  Nivel intermedio           Soltero               1   
438460     6841878    22    Nivel superior           Soltero               1   
438461     6842765    59  Nivel intermedio            Casado               2   
438462     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado                Otro             12   
2                Empleado           Seguridad              3   
3        Business Partner              Ventas              8   
4        Business Partner              Ventas              8   
...                   ...                 ...            ...   
438458        Pensionista                Otro              0   
438459           Empleado  Construcción Civil              8   
438460   Business Partner              Ventas              1   
438461        Pensionista                Otro              0   
438462           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                427500.0            1    Departamento alquilado  
2                112500.0            1  Casa/Departamento propio  
3                270000.0            0  Casa/Departamento propio  
4                270000.0            0  Casa/Departamento propio  
...                   ...          ...                       ...  
438458           135000.0            0  Casa/Departamento propio  
438459           103500.0            0  Casa/Departamento propio  
438460            54000.0            0       Vive con los padres  
438461            72000.0            0  Casa/Departamento propio  
438462           121500.0            0  Casa/Departamento propio  

[438463 rows x 11 columns]

In [33]:
##Borrando registros
from sqlalchemy.exc import SQLAlchemyError
query ="DELETE FROM clientes WHERE ID_Cliente=5008804"
try:
    r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
    print(e)
else:
  print("Numeros de registros borrados: ", r_set.rowcount)

Numeros de registros borrados:  1


In [35]:
from sqlalchemy.exc import SQLAlchemyError
query ="DELETE FROM clientes WHERE ID_Cliente=5008804"
try:
    r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
    print(e)
else:
  print("Numeros de registros borrados: ", r_set.rowcount)

Numeros de registros borrados:  0


In [36]:
pd.read_sql_table('clientes', con=engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008805    32    Nivel superior  Relación-estable               2   
1          5008806    58  Nivel intermedio            Casado               2   
2          5008808    52  Nivel intermedio           Soltero               1   
3          5008809    52  Nivel intermedio           Soltero               1   
4          5008810    52  Nivel intermedio           Soltero               1   
...            ...   ...               ...               ...             ...   
438457     6840104    62  Nivel intermedio        Divorciado               1   
438458     6840222    43  Nivel intermedio           Soltero               1   
438459     6841878    22    Nivel superior           Soltero               1   
438460     6842765    59  Nivel intermedio            Casado               2   
438461     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado           Seguridad              3   
2        Business Partner              Ventas              8   
3        Business Partner              Ventas              8   
4        Business Partner              Ventas              8   
...                   ...                 ...            ...   
438457        Pensionista                Otro              0   
438458           Empleado  Construcción Civil              8   
438459   Business Partner              Ventas              1   
438460        Pensionista                Otro              0   
438461           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                112500.0            1  Casa/Departamento propio  
2                270000.0            0  Casa/Departamento propio  
3                270000.0            0  Casa/Departamento propio  
4                270000.0            0  Casa/Departamento propio  
...                   ...          ...                       ...  
438457           135000.0            0  Casa/Departamento propio  
438458           103500.0            0  Casa/Departamento propio  
438459            54000.0            0       Vive con los padres  
438460            72000.0            0  Casa/Departamento propio  
438461           121500.0            0  Casa/Departamento propio  

[438462 rows x 11 columns]

In [37]:
##Actualizando registros
query ="UPDATE clientes SET Grado_estudio='Nivel superior' WHERE ID_Cliente=5008808"
try:
    r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
    print(e)
else:
  print("Numeros de registros actualizados: ", r_set.rowcount)

Numeros de registros actualizados:  1


In [38]:
pd.read_sql_table('clientes', con=engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008805    32    Nivel superior  Relación-estable               2   
1          5008806    58  Nivel intermedio            Casado               2   
2          5008808    52    Nivel superior           Soltero               1   
3          5008809    52  Nivel intermedio           Soltero               1   
4          5008810    52  Nivel intermedio           Soltero               1   
...            ...   ...               ...               ...             ...   
438457     6840104    62  Nivel intermedio        Divorciado               1   
438458     6840222    43  Nivel intermedio           Soltero               1   
438459     6841878    22    Nivel superior           Soltero               1   
438460     6842765    59  Nivel intermedio            Casado               2   
438461     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado           Seguridad              3   
2        Business Partner              Ventas              8   
3        Business Partner              Ventas              8   
4        Business Partner              Ventas              8   
...                   ...                 ...            ...   
438457        Pensionista                Otro              0   
438458           Empleado  Construcción Civil              8   
438459   Business Partner              Ventas              1   
438460        Pensionista                Otro              0   
438461           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                112500.0            1  Casa/Departamento propio  
2                270000.0            0  Casa/Departamento propio  
3                270000.0            0  Casa/Departamento propio  
4                270000.0            0  Casa/Departamento propio  
...                   ...          ...                       ...  
438457           135000.0            0  Casa/Departamento propio  
438458           103500.0            0  Casa/Departamento propio  
438459            54000.0            0       Vive con los padres  
438460            72000.0            0  Casa/Departamento propio  
438461           121500.0            0  Casa/Departamento propio  

[438462 rows x 11 columns]

In [39]:
inspector = inspect(engine)
print(inspector.get_table_names())


['clientes', 'empleados']


##Desafio manipulando una base de datos

Es el momento de poner a prueba tus conocimientos adquiridos durante la clase.

Usted es responsable de crear una base de datos local de clientes para una institución financiera. Disponemos del archivo CSV con los datos de los clientes.

Tu misión es:

Crear la base de datos local con la biblioteca SQLAlchemy.
Escribir los datos del archivo CSV en esta base de datos local.
Realizar tres actualizaciones en la base de datos:
Actualizar el registro del cliente ID 6840104 cuyo rendimiento anual cambió a 300000.
Eliminar el registro de cliente ID 5008809, ya que esta persona ya no tiene cuenta en la institución financiera.
Crear un nuevo registro de cliente siguiendo las especificaciones a continuación:
ID_cliente: 6850985
Edad: 33
Grado_estudio: Doctorado
Estado_civil: Soltero
Tamaño_familia: 1
Categoria_de_renta: Empleado
Ocupacion: TI
Años_empleado: 2
Rendimiento_anual: 290000
Tiene_carro: 0
Vivienda: Casa/Departamento propio

Consejo importante: Para agregar un nuevo cliente a la tabla, use la cláusula INSERT INTO seguida del nombre de la tabla y luego especifique los nombres de las columnas de la tabla entre paréntesis. Utilice la cláusula VALUES y luego pase entre paréntesis los nuevos valores para este nuevo registro. Asegúrese de que los valores estén en el orden correcto y en el formato adecuado para cada columna.

In [41]:
##Para crear la base de datos local es necesario ejecutar los siguientes comandos. Este código consiste en importar la biblioteca sqlalchemy y crear un objeto engine
##que representa una conexión a una base de datos SQLite en memoria. El método create_engine se utiliza para crear el objeto engine y especificar la base de datos
##que se utilizará. En este caso, la base de datos es una base de datos SQLite en memoria, que se crea usando sqlite:///:memory::
import sqlalchemy
from sqlalchemy import create_engine, MetaData, Table, inspect, text
engine = create_engine('sqlite:///:memory:')

In [42]:
##A continuación, podemos leer los datos con la función read_csv y escribirlos en el formato de la base de datos con la función to_sql:
import pandas as pd
archivo = '/content/drive/MyDrive/CIENCIA DE DATOS/PANDAS/clientes_banco.csv'
datos = pd.read_csv(archivo)
datos.to_sql('clientes', engine, index=False)

438463

In [ ]:
##Después de crear la tabla, podemos obtener un DataFrame con la función read_sql_table:
pd.read_sql_table('clientes', con=engine.connect())

¡Ahora vamos a comenzar las actualizaciones de la base de datos!

Actualizar el registro del cliente ID 6840104 cuyo rendimiento anual cambió a 300000:

El siguiente código actualiza el rendimiento anual del ID de cliente 6840104 en la tabla clientes. La variable query contiene una declaración SQL que actualiza ese registro. Luego, la declaración engine.connect() se usa para crear una conexión a la base de datos SQLite. Finalmente, la declaración .execute(text(query)) se utiliza para ejecutar la declaración SQL contenida en la variable query y actualizar el registro en la tabla clientes.

In [44]:
from sqlalchemy.exc import SQLAlchemyError
query = 'UPDATE clientes SET Rendimiento_anual=300000.0 WHERE ID_Cliente=6840104'
try:
  r_set=engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros actualizados: ",r_set.rowcount)

#Registros actualizados:  1


In [45]:
##Eliminar el registro de cliente ID 5008809, ya que esta persona ya no tiene una cuenta en la institución financiera:
from sqlalchemy.exc import SQLAlchemyError
query = 'DELETE FROM clientes WHERE ID_Cliente=5008809'
try:
  r_set=engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros borrados: ",r_set.rowcount)

#Registros borrados:  1


Cree un nuevo registro de cliente siguiendo las especificaciones dadas anteriormente:

Al trabajar con bases de datos, es común necesitar insertar nuevos registros en nuestras tablas. Para ello podemos utilizar la cláusula INSERT INTO que nos permite añadir nuevos datos de forma práctica y rápida.

Para utilizar esta cláusula, primero debe especificar el nombre de la tabla en la que se insertará el registro. A continuación, debemos pasar entre paréntesis los nombres de las columnas donde se agregarán los nuevos valores. Es importante recordar que el orden de los nombres debe ser el mismo orden en el que se pasarán los valores.

Después de especificar las columnas, usamos la cláusula VALUES para agregar los nuevos valores. Nuevamente debemos pasar entre paréntesis los valores a insertar en el mismo orden en que se especificaron las columnas. Es importante asegurarse de que los valores estén en el formato correcto para cada tipo de datos.


```
Como la `query` es larga, puedes usar `' \` para indicar que el código continúa en la siguiente línea.
```



In [46]:
from sqlalchemy.exc import SQLAlchemyError
query = 'INSERT INTO clientes (ID_Cliente, Edad, Grado_estudio, Estado_civil, ' \
        'Tamaño_familia, Categoria_de_renta, Ocupacion, Años_empleado, ' \
        'Rendimiento_anual, Tiene_carro, Vivienda) ' \
        'VALUES (6850985, 33, "Doctorado", "Soltero", 1, "Empleado", "TI", ' \
        '2, 290000, 0, "Casa/Departamento propio")'

try:
  r_set=engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros insertados: ",r_set.rowcount)

#Registros insertados:  1


In [47]:
pd.read_sql_table('clientes', con=engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804    32    Nivel superior  Relación-estable               2   
1          5008805    32    Nivel superior  Relación-estable               2   
2          5008806    58  Nivel intermedio            Casado               2   
3          5008808    52  Nivel intermedio           Soltero               1   
4          5008810    52  Nivel intermedio           Soltero               1   
...            ...   ...               ...               ...             ...   
438458     6840222    43  Nivel intermedio           Soltero               1   
438459     6841878    22    Nivel superior           Soltero               1   
438460     6842765    59  Nivel intermedio            Casado               2   
438461     6842885    51  Nivel intermedio            Casado               2   
438462     6850985    33         Doctorado           Soltero               1   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado                Otro             12   
2                Empleado           Seguridad              3   
3        Business Partner              Ventas              8   
4        Business Partner              Ventas              8   
...                   ...                 ...            ...   
438458           Empleado  Construcción Civil              8   
438459   Business Partner              Ventas              1   
438460        Pensionista                Otro              0   
438461           Empleado              Ventas              3   
438462           Empleado                  TI              2   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                427500.0            1    Departamento alquilado  
2                112500.0            1  Casa/Departamento propio  
3                270000.0            0  Casa/Departamento propio  
4                270000.0            0  Casa/Departamento propio  
...                   ...          ...                       ...  
438458           103500.0            0  Casa/Departamento propio  
438459            54000.0            0       Vive con los padres  
438460            72000.0            0  Casa/Departamento propio  
438461           121500.0            0  Casa/Departamento propio  
438462           290000.0            0  Casa/Departamento propio  

[438463 rows x 11 columns]